export const paginationDefaults = {
  total: 0,
  itemsPerPage: 10,
  siblingCount: 2,
  showEdges: true,
  disabled: false,
  showControls: true,
  color: undefined,
  variant: 'outline' as const,
  size: 'md' as const,
  severity: 'primary' as const,
  activeColor: undefined,
  activeVariant: 'solid' as const,
  firstIcon: { name: 'chevronsLeft' } as const,
  previousIcon: { name: 'chevronLeft' } as const,
  nextIcon: { name: 'chevronRight' } as const,
  lastIcon: { name: 'chevronsRight' } as const,
  ellipsisIcon: { name: 'moreHorizontal' } as const,
  ui: undefined,
}
