export const popoverDefaults = {
  modal: false,
  showArrow: false,
  align: 'center' as const,
  alignFlip: true,
  alignOffset: 0,
  arrowPadding: 0,
  avoidCollisions: true,
  arrowWidth: 10,
  arrowHeight: 5,
  arrowRounded: false,
  collisionPadding: 8,
  disableUpdateOnLayoutShift: false,
  hideShiftedArrow: true,
  hideWhenDetached: false,
  positionStrategy: 'fixed' as const,
  prioritizePosition: false,
  side: 'bottom' as const,
  sideFlip: true,
  sideOffset: 4,
  sticky: 'partial' as const,
  updatePositionStrategy: 'optimized' as const,
}
