export const tooltipDefaults = {
  delayDuration: 0,
  withArrow: true,
  disableClosingTrigger: false,
  disabled: false,
  ignoreNonKeyboardFocus: false,
  align: 'center',
  alignOffset: 0,
  arrowPadding: 0,
  avoidCollisions: true,
  collisionPadding: 0,
  forceMount: false,
  hideWhenDetached: false,
  positionStrategy: 'fixed',
  side: 'top',
  sideOffset: 2,
  sticky: 'partial',
  updatePositionStrategy: 'optimized',
  arrowWidth: 10,
  arrowHeight: 5,
  ui: undefined,
}
