export const dropdownMenuDefaults = {
  modal: true,
  disabled: false,
  align: 'center' as const,
  alignFlip: true,
  alignOffset: 0,
  arrowPadding: 0,
  avoidCollisions: true,
  collisionBoundary: () => [],
  collisionPadding: 0,
  disableUpdateOnLayoutShift: false,
  hideShiftedArrow: true,
  hideWhenDetached: false,
  loop: false,
  positionStrategy: 'fixed' as const,
  prioritizePosition: false,
  side: 'bottom' as const,
  sideFlip: true,
  sideOffset: 0,
  sticky: 'partial' as const,
  updatePositionStrategy: 'optimized' as const,
}
