import {
  AlertTriangle,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsLeft,
  ChevronsRight,
  CircleAlert,
  CircleCheck,
  Info,
  LoaderCircle,
  Save,
  Search,
  Trash2,
  X,
  Minus,
  Plus,
  MoreHorizontal,
  User,
  Upload,
  File,
  FileText,
  FileArchive,
  FileSpreadsheet,
  Image,
  AudioLines,
  Video,
} from '@lucide/vue'

export const ICONS = {
  warning: AlertTriangle,
  check: Check,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  chevronRight: ChevronRight,
  chevronLeft: ChevronLeft,
  chevronsLeft: ChevronsLeft,
  chevronsRight: ChevronsRight,
  error: CircleAlert,
  success: CircleCheck,
  info: Info,
  spinner: LoaderCircle,
  save: Save,
  search: Search,
  trash2: Trash2,
  x: X,
  minus: Minus,
  plus: Plus,
  moreHorizontal: MoreHorizontal,
  user: User,
  upload: Upload,
  file: File,
  fileText: FileText,
  fileArchive: FileArchive,
  fileSpreadsheet: FileSpreadsheet,
  image: Image,
  audio: AudioLines,
  video: Video,
} as const

export type IconName = keyof typeof ICONS
