import {
  AlertTriangle,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsLeft,
  ChevronsRight,
  CircleAlert,
  CircleCheck,
  Info,
  LoaderCircle,
  Save,
  Search,
  Trash2,
  X,
  Minus,
  MoreHorizontal,
} from '@lucide/vue'

export const ICONS = {
  warning: AlertTriangle,
  check: Check,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  chevronRight: ChevronRight,
  chevronLeft: ChevronLeft,
  chevronsLeft: ChevronsLeft,
  chevronsRight: ChevronsRight,
  error: CircleAlert,
  success: CircleCheck,
  info: Info,
  spinner: LoaderCircle,
  save: Save,
  search: Search,
  trash2: Trash2,
  x: X,
  minus: Minus,
  moreHorizontal: MoreHorizontal,
} as const

export type IconName = keyof typeof ICONS
