export const toastDefaults = {
  open: true,
  duration: 5000,
  type: 'foreground' as const,
  variant: 'soft' as const,
  severity: 'primary' as const,
  color: undefined,
  position: 'bottom-right' as const,
  label: undefined,
  description: undefined,
  icon: undefined,
  closeButton: undefined,
  progress: false,
  closable: true,
  disableSwipe: false,
  swipeDirection: 'right' as const,
  swipeThreshold: 50,
  hotkey: () => ['F8'],
  labelHotkey: 'Notifications ({hotkey})',
  ui: undefined,
}
