import './assets/css/styles.css'

export * from '@/components/app/Alerta'
export * from '@/components/app/Avatar'
export * from '@/components/app/Boton'
export * from '@/components/app/Checkbox'
export * from '@/components/app/Icono'
export * from '@/components/app/Kbd'
export * from '@/components/app/Label'
export * from '@/components/app/Separador'
export * from '@/components/app/Switch'
export * from '@/components/app/Etiqueta'
export * from '@/components/app/Tarjeta'
export * from '@/components/app/Tooltip'

export { obtenerColorContraste } from '@/composables'
