export const listboxDefaults = {
  size: 'md' as const,
  severity: 'primary' as const,
  disabled: false,
  name: undefined,
  required: false,
  multiple: false,
  orientation: 'vertical' as const,
  selectionBehavior: 'toggle' as const,
  highlightOnHover: true,
  loading: false,
  filter: false,
  ignoreFilter: false,
  items: () => [],
  groups: () => [],
  ui: undefined,
} as const
